# Generated by Django 3.0.8 on 2020-08-24 14:57

from django.db import migrations, models
import encyclopedia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', encyclopedia.models.CICharField(max_length=20, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
